version: '3.7'
services:
  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: quotes
    ports:
      - 27017:27017
    volumes:
      - ./data_files:/data/db